import { Flight } from "./Flight";

const FlightArrivals: Flight[] = [
    {
        id: 1,
        airline: "Lufthansa",
        flightNumber: "LH 2037",
        from: "STR",
        to: "MUC",
        plannedArrival: new Date("2021-05-01T12:00:00"),
        realArrival: new Date("2021-05-01T12:00:00"),
        status: "Landed",
        terminal: "2",
        gate: "G09",
        carousel: "3",
        checkIn: "A",
        checkInDesk: "A01",
        checkInTime: new Date("2021-05-01T12:00:00"),
        baggageClaim: "3",
        logo: "https://www.lufthansa.com/etc/designs/lh-rwd/images/lufthansa-logo.svg",
    },
    {
        id: 2,
        airline: "Germanwings",
        flightNumber: "4U 2037",
        from: "BER",
        to: "MUC",
        plannedArrival: new Date("2021-05-01T12:00:00"),
        realArrival: new Date("2021-05-01T12:00:00"),
        status: "Baggage Claim",
        terminal: "1",
        gate: "A09",
        carousel: "3",
        checkIn: "A",
        checkInDesk: "A01",
        checkInTime: new Date("2021-05-01T12:00:00"),
        baggageClaim: "3",
        logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Germanwings_logo.svg/1200px-Germanwings_logo.svg.png",
    },
    {
        id: 3,
        airline: "British Airways",
        flightNumber: "BA 2037",
        from: "LHR",
        to: "MUC",
        plannedArrival: new Date("2021-05-01T12:00:00"),
        realArrival: new Date("2021-05-01T12:00:00"),
        status: "Scheduled",
        terminal: "1",
        gate: "A09",
        carousel: "3",
        checkIn: "A",
        checkInDesk: "A01",
        checkInTime: new Date("2021-05-01T12:00:00"),
        baggageClaim: "3",
        logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Germanwings_logo.svg/1200px-Germanwings_logo.svg.png",
    },
    {
        id: 4,
        airline: "Air France",
        flightNumber: "AF 2037",
        from: "CDG",
        to: "MUC",
        plannedArrival: new Date("2021-05-01T12:00:00"),
        realArrival: new Date("2021-05-01T12:00:00"),
        status: "Delayed",
        terminal: "1",
        gate: "A09",
        carousel: "3",
        checkIn: "A",
        checkInDesk: "A01",
        checkInTime: new Date("2021-05-01T12:00:00"),
        baggageClaim: "3",
        logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Germanwings_logo.svg/1200px-Germanwings_logo.svg.png",
        estimatedArrival: new Date("2021-05-01T12:30:00"),
    },
    {
        id: 5,
        airline: "Emirates",
        from: "DXB",
        to: "MUC",
        flightNumber: "EK 2037",
        plannedArrival: new Date("2021-05-01T12:00:00"),
        realArrival: new Date("2021-05-01T12:00:00"),
        status: "Cancelled",
        terminal: "1",
        gate: "A09",
        carousel: "3",
        checkIn: "A",
        checkInDesk: "A01",
        checkInTime: new Date("2021-05-01T12:00:00"),
        baggageClaim: "3",
        logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Germanwings_logo.svg/1200px-Germanwings_logo.svg.png",
    },
    {
        id: 6,
        airline: "Turkish Airlines",
        flightNumber: "TK 2037",
        from: "IST",
        to: "MUC",
        plannedArrival: new Date("2021-05-01T12:00:00"),
        realArrival: new Date("2021-05-01T12:00:00"),
        status: "Diverted",
        terminal: "1",
        gate: "A09",
        carousel: "3",
        checkIn: "A",
        checkInDesk: "A01",
        checkInTime: new Date("2021-05-01T12:00:00"),
        baggageClaim: "3",
        logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Germanwings_logo.svg/1200px-Germanwings_logo.svg.png",
    },
    {
        id: 7,
        airline: "Austrian Airlines",
        flightNumber: "OS 2037",
        from: "VIE",
        to: "MUC",
        plannedArrival: new Date("2021-05-01T12:00:00"),
        realArrival: new Date("2021-05-01T12:30:00"),
        status: "Delayed",
        terminal: "1",
        gate: "A09",
        carousel: "3",
        checkIn: "A",
        checkInDesk: "A01",
        checkInTime: new Date("2021-05-01T12:00:00"),
        baggageClaim: "3",
        logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Germanwings_logo.svg/1200px-Germanwings_logo.svg.png",
    }
];

export {
    FlightArrivals
};